// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgirxXXMao9hePQHE8IGQ_c5Z9-Uxfhk',
    appId: '1:922764653098:web:2c4cc78f7057eef00f0953',
    messagingSenderId: '922764653098',
    projectId: 'five-stars-f150c',
    authDomain: 'five-stars-f150c.firebaseapp.com',
    storageBucket: 'five-stars-f150c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVu4GAm1Q_3Kn0MH6DtMMjAOk8Dc9E-E',
    appId: '1:922764653098:android:6ed4abae80c175300f0953',
    messagingSenderId: '922764653098',
    projectId: 'five-stars-f150c',
    storageBucket: 'five-stars-f150c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByru2hiXor5cCxfPmuqMAV3RkhR7ukK5E',
    appId: '1:922764653098:ios:69ad72555cb0b0ff0f0953',
    messagingSenderId: '922764653098',
    projectId: 'five-stars-f150c',
    storageBucket: 'five-stars-f150c.appspot.com',
    iosBundleId: 'com.example.adminManager',
  );
}
