// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJZoW2Us_RDSzob0MKNO3hoquS3IRiY1g',
    appId: '1:845852301973:web:907b1098e1c2e602e0999c',
    messagingSenderId: '845852301973',
    projectId: 'cinqetoileapp',
    authDomain: 'cinqetoileapp.firebaseapp.com',
    storageBucket: 'cinqetoileapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVka0fYewL1s7yz2kRlewncqDpZAicmA',
    appId: '1:845852301973:android:899e47e8532dc2f9e0999c',
    messagingSenderId: '845852301973',
    projectId: 'cinqetoileapp',
    storageBucket: 'cinqetoileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQB9U4e6O8c12Ly1X2DF0GPYopmb289-s',
    appId: '1:845852301973:ios:599827ae19da51b2e0999c',
    messagingSenderId: '845852301973',
    projectId: 'cinqetoileapp',
    storageBucket: 'cinqetoileapp.appspot.com',
    iosBundleId: 'com.example.adminManager',
  );

}